version: 0.2

env:
  variables:
    stage: PRE_PROD
  parameter-store:
    SLS_KEY: sls_key_param
    SLS_SECRET: sls_secret_param

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:

      # Upgrade AWS CLI to the latest version
      - pip3 install --upgrade awscli
      - pip3 install -r requirements.txt

      # install nodejs and npm
      - yum install nodejs
      - yum install npm

      # install serverless here
      - npm install -g serverless
      - npm update -g serverless

      - serverless create --template aws-python3

      #install wsgi plugin
      - sls plugin install -n serverless-wsgi

      #install serverless-python-requirements plugin
      - sls plugin install -n serverless-python-requirements

      #install env variables plugin
      - serverless install -u https://github.com/serverless/examples/tree/master/aws-node-env-variables -n  aws-node-env-variables


  pre_build:
    commands:

      # Discover and run unit tests in the 'tests' directory. For more information, see <https://docs.python.org/3/library/unittest.html#test-discovery>
      - python3 -m unittest discover tests
  
      # Discover versions
      - node --version
      - npm --version
      - serverless --version
      - python3 --version

  build:
    commands:

      - serverless config credentials --provider aws --key $SLS_KEY --secret $SLS_SECRET
      - serverless deploy list

      # Use AWS SAM to package the application by using AWS CloudFormation
      - aws cloudformation package --template template.yml --s3-bucket $S3_BUCKET --output-template template-export.yml

      # Do not remove this statement. This command is required for AWS CodeStar projects.
      # Update the AWS Partition, AWS Region, account ID and project ID in the project ARN on template-configuration.json file so AWS CloudFormation can tag project resources.
      - sed -i.bak 's/\$PARTITION\$/'${PARTITION}'/g;s/\$AWS_REGION\$/'${AWS_REGION}'/g;s/\$ACCOUNT_ID\$/'${ACCOUNT_ID}'/g;s/\$PROJECT_ID\$/'${PROJECT_ID}'/g' template-configuration.json

artifacts:
  files:
    - serverless.yml
    - template-export.yml
    - template-configuration.json