-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQglKVsKzSpp+URvZUp
WTWdWmtJD3bDLi/pR/0qn5f1L5GgCgYIKoZIzj0DAQehRANCAARVmFN3lCbDDuxS
hhQkRNm43aIrPranyNIvaZ1DpDH4te+2uQQkv0tuQ3oaGNpGuGEHL1AgtQ57/32n
zpTVXiGl
-----END PRIVATE KEY-----